### ISSUE TITLE
Change the default Windows key binding

### ISSUE THREAD

**Issue by ionut-botizan** [steve8708/vscode-align#1]
Pressing `Alt+Ctrl` is the equivalent of pressing [`AltGr`](https://en.wikipedia.org/wiki/AltGr_key) (the `Alt` key on the right side of the keyboard), which is used as a modifier to input custom characters on international keyboards.
For example, in my case (using the "ROP - Romanian Programmers" keyboard layout), `Alt + Ctrl + A` (`AltGr + A`) should insert the Latin letter **ă**, but that behavior is hijacked by the extension.

I suggest changing the shortcut to `Ctrl + Shift + A`.

---
## Temporary Workaround

Go to `File > Preferences > User settings` and add the following snippet to set `Ctrl+Shift+A` as your shortcut and remove the default one.

``` javascript
{ "key": "ctrl+shift+a",          "command": "extension.align",
                                     "when": "editorTextFocus" },

{ "key": "ctrl+alt+a",            "command": "",
                                     "when": "editorTextFocus" }
```

**Comment by pelletiermaxime** [comment]
I also much prefer ctrl+shift+a. Imo how to change the shortcut should be documented in the README.

Thanks!
