### ISSUE TITLE
Alignment only works if I have have the entire lines selected

### ISSUE THREAD

**Issue by ShimShamSam** [steve8708/vscode-align#3]
All other alignment tools I've used in other IDEs work even if I've only partially selected a line. Your plugin seems to fail if I don't select the entirety of all lines, including indentation. This is even more of a hassle since the Home key needs to be pressed twice in order to select the indentation if you're using the keyboard to maneuver.

**Comment by ionut-botizan** [comment]
+1

**Comment by TheColorRed** [comment]
+1

**Comment by steve8708** [comment]
Fixed via  #6
