### ISSUE TITLE
Mimic atom-alignment instead

### ISSUE THREAD

**Issue by csholmq** [steve8708/vscode-align#5]
I would suggest you adapt your extension to instead mimic [atom-alignment](https://atom.io/packages/atom-alignment) rather than [Atom Alignment](https://atom.io/packages/alignment). Much simpler handling (no issues with tabs, identifying delimiters, etc) but only align all text according to multiple cursors/selections.

Here's an example where I press `ctrl+d` to select all instances of the current word (in this case =). Then I do an align by pressing `ctrl+alt+a`.

![atom-align](https://cloud.githubusercontent.com/assets/1297882/12889206/283074cc-ce7e-11e5-8157-bdca20675291.gif)

This would also solve https://github.com/steve8708/vscode-align/issues/4

![atom-align2](https://cloud.githubusercontent.com/assets/1297882/12889323/9cddbc80-ce7e-11e5-9847-13eb0d3b2653.gif)

**Comment by steve8708** [comment]
Very interesting idea!

@csholmq does atom-alignment support delimiters as well (e.g. when whole lines are selected) or only multi cursor selection based alignment?

I have a fix in mind for the other issue so I'm wondering if this plugin should support both (delimiter based when multi lines are selected in a single cursor, and cursor based there are multiple cursors in the active editor)

what do you think?

**Comment by steve8708** [comment]
Also, @csholmq what do you you use to make those awesome gifs of your screen? :smile:

**Comment by csholmq** [comment]
@steve8708 Yes, it does. But as you can see it does a different job than my previous GIF.

![align_multiline](https://cloud.githubusercontent.com/assets/1297882/12895166/3aaf3dbe-ce9b-11e5-8b4d-8f95f3d3729a.gif)

Supporting both sounds like a great idea!

I use [LICEcap]() which is available on both Windows and OS X. It's nice and neat!

**Comment by blakeembrey** [comment]
I just discovered this, but I think it'd make sense to support both. I'd be happy to create a package that can be consumed from the Atom module source code so we both have consistent behaviour. I also like the manual selection behaviour - so having both sounds good. Maybe detect based on whether multiple lines and multiple cursors are available?

**Comment by steve8708** [comment]
@blakeembrey that would be amazing. That would without a doubt fix any/all underlying issues here and make the behavior perfectly consistent and consolidate our efforts

I am currently using [text-table](https://github.com/aptinio/text-table) for the alignment in this plugin but as seen in this issue it is not perfectly fitted for it's purpose

If you make a package to support both I would be very happy to integrate it!

Also, totally agree on supporting both based automatically based on wether multiple cursors or a multi line single selection(s) exists in the active editor

**Comment by blakeembrey** [comment]
I just pushed https://github.com/blakeembrey/node-alignment, it's just a completely copied conversion from the Atom module right now. There can easily be more "modes" added, as well as an "auto" mode.

**Comment by csholmq** [comment]
:+1:

**Comment by steve8708** [comment]
Amazing, thanks @blakeembrey!

I'm a bit inundated with work at the moment, but I will get to migrating to your node alignment package soonest I can

I'm happy to take PRs too @csholmq if you have time to hook this up (it should be a somewhat simple swap that you can find in src/extension.ts) if you are able to find the time before I can

thanks again all!

**Comment by csholmq** [comment]
I'll have a go. Would be great if @blakeembrey could implement support for cursor alignment as well.

**Comment by blakeembrey** [comment]
I'm not sure I'll have time in the immediate future, but I'd accept a PR. Should just be a function that takes a string and range positions, then executes similar splitting logic as before.

**Comment by steve8708** [comment]
now fixed via  #6
